name: unplugged-afk
version: '${version}'

main: dev.detpikachu.unpluggedAfk.UnpluggedAfk
api-version: '${apiVersion}'
load: POSTWORLD

permissions:
  unplugged-afk.unplug:
    description: Gives access to the '/unplug' player command
    default: true
  unplugged-afk.admin:
    description: Gives access to all admin commands
    children:
      unplugged-afk.admin.info: true
      unplugged-afk.admin.debug: true
  unplugged-afk.admin.info:
    description: Gives access to the '/unplugged info' admin command
  unplugged-afk.admin.debug:
    description: Gives access to the '/unplugged debug' admin command and its subcommands
