name: unplugged-afk
version: '${version}'

main: dev.detpikachu.unpluggedAfk.UnpluggedAfk
api-version: '1.21.11'
load: POSTWORLD

permissions:
  unplugged-afk.unplug:
    description: Gives access to the '/unplug' player command
    default: true
  unplugged-afk.admin:
    description: Gives access to all admin commands
    children:
      unplugged-afk.admin.info: true
      unplugged-afk.admin.debug: true
