name: unplugged-afk
version: '${version}'
description: Save electricity by disconnecting from the server and leaving your character to do the AFKing for you!
author: Andrei "detpikachu" Hava
website: https://github.com/devpikachu/unplugged-afk-paper

main: dev.detpikachu.unpluggedafk.UnpluggedAfk
api-version: '${apiVersion}'
load: POSTWORLD
softdepend: [packetevents, HuskSync, PlaceholderAPI, LuckPerms, MiniPlaceholders]

permissions:
  unplugged-afk.unplug:
    description: Gives access to the '/unplug' player command
    default: true
  unplugged-afk.admin:
    description: Gives access to all admin commands
    children:
      unplugged-afk.admin.info: true
      unplugged-afk.admin.list: true
      unplugged-afk.admin.debug: true
  unplugged-afk.admin.info:
    description: Gives access to the '/unplugged info' admin command
  unplugged-afk.admin.list:
    description: Gives access to the '/unplugged list' admin command
  unplugged-afk.admin.debug:
    description: Gives access to the '/unplugged debug' admin command and its subcommands
